-- phpMyAdmin SQL Dump
-- version 2.6.4-pl4-Debian-2
-- http://www.phpmyadmin.net
-- 
-- Serveur: sql-1.verygames.net
-- Généré le : Mercredi 11 Janvier 2006 à 20:28
-- Version du serveur: 4.1.15
-- Version de PHP: 4.4.0-4
-- 
-- Base de données: `server60`
-- 

-- --------------------------------------------------------

-- 
-- Structure de la table `adhesion_adherents`
-- 

CREATE TABLE "adhesion_adherents" (
  "adh_id" int(11) NOT NULL default '0',
  "adh_nom" varchar(40) NOT NULL default '',
  "adh_prenom" varchar(30) NOT NULL default '',
  "adh_adresse" varchar(100) NOT NULL default '',
  "adh_code_postal" varchar(10) NOT NULL default '',
  "adh_ville" varchar(30) NOT NULL default '',
  "adh_pays" varchar(20) NOT NULL default '',
  "adh_sexe" char(1) NOT NULL default '',
  "adh_email" varchar(100) NOT NULL default '',
  "adh_pseudo" varchar(30) NOT NULL default '',
  "adh_equipe" varchar(30) NOT NULL default '',
  "adh_statut" int(11) NOT NULL default '2',
  "adh_date_naissance" date NOT NULL default '0000-00-00',
  "adh_telephone_fixe" varchar(14) NOT NULL default '',
  "adh_telephone_portable" varchar(14) NOT NULL default '',
  PRIMARY KEY  ("adh_id"),
  KEY "pseudo" ("adh_pseudo")
);

-- 
-- Contenu de la table `adhesion_adherents`
-- 

INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (2, 'Dorso', 'Erwan', '46 bis rue Jacques Provost', '31200', 'toulouse', 'france', 'H', 'heroined@mageos.com', 'karamazov', '7', 1, '1975-10-26', '0534309159', '0663875230');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (65, 'Spengler', 'Fabien', '53 rue planchat', '75020', 'Paris', 'France', 'H', 'fab.mail@laposte.fr', 'KlocheTTe', '3', 1, '1975-03-13', '0870370535', '0622230535');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (3, 'Montadre', 'Sébastien', '43 rue Ernest Renan', '92190', 'Meudon', 'France', 'H', 'slapinou@gmail.com', 'Slapinou', '3', 1, '1979-10-03', '0145078609', '0684476845');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (59, 'Carry', 'Lionel', '6 bis rue Robert Julien', '92190', 'Meudon', 'France', 'H', 'coeurdelio@hotmail.com', 'Lilo', '3', 2, '1980-05-09', '0145346087', '0660233488');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (7, 'LEAUTE', 'Sébastien', '202 rue Hector Berlioz', '41100', 'Vendome', 'France', 'H', 'macleote@msn.com', 'GPX', '3', 1, '1976-11-21', '0254731326', '0611178984');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (45, 'DEBOVE', 'Florent', '10 rue Mulet', '38460', 'CREMIEU', 'FRANCE', 'H', 'korozif@ekt.fr.st', 'KoRoZiF', '17', 1, '1969-09-21', '0437061162', '0665005120');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (13, 'GRIFFOULIERE', 'Guillaume', '20 rue du Saget', '74100', 'Annemasse', 'France', 'H', 'coredumped@culmouton.com', 'Core Dumped', '7', 2, '1979-03-02', '0450375293', '0612337039');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (14, 'Desneux', 'Nicolas', 'Indianapolis', 'c''est usa.', 'Indianapolis/Tours', 'USA', 'H', 'nicux@msn.com', 'Nicux', '7', 2, '1975-01-19', 'nothing', 'nothing');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (44, 'Moerman', 'Alain', '45 rue neuve', '44320', 'st pere en retz', 'France', 'F', 'inscription.lettre@wanadoo.fr', 'ZuuR', '17', 2, '1971-02-25', '', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (12, 'Lenoir', 'Jean-Christophe', '125, rue Goerge Sand', '37000', 'Tours', 'France', 'H', 'jcex@culmouton.com', 'JCex', '7', 1, '1978-05-03', '0234381121', '0664320503');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (21, 'Dumont', 'Philippe', '8, rue de la Paix', '63910', 'Vertaizon', 'France', 'H', 'campbell@culmouton.com', 'Campbell', '14', 1, '1981-05-12', '', '0662520439');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (19, 'LETOURNEL', 'Julien', '2 bd Jean Bouin', '77370', 'NANGIS', 'France', 'H', 'makaveli@24kra.net', 'makaveLi', '3', 2, '1985-02-17', '0164081220', '0683203519');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (30, 'Morel', 'Aurélien', 'Rue du Midi 17b', '1400', 'Yverdon', 'Suisse', '', 'aurelien.morel@freesurf.ch', 'Olmolism', '4', 1, '1980-09-15', '', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (31, 'Cabrelli', 'Clément', '82 rue des roissys', '92320', 'chatillon', 'france', 'H', 'skax@brutalrush.com', 'SkaX', '7', 2, '1981-03-07', '0158882899', '0622088871');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (18, 'Taleb', 'Kamel', '3 allée du languedoc', '95310', 'Saint ouen l''aumône', 'France', 'H', 'tounsi007@msn.com', 'Onkyo', '4', 2, '1978-09-16', '0134300653', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (37, 'Louison-François', 'Mickaël', '72 rue Bernard Palissy', '37000', 'TOURS', 'France', 'H', 'its.m@wanadoo.fr', 'ITS', '4', 1, '1973-09-02', '', '0661717630');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (81, 'Chaffiol', 'Antoine', '6 rue maurice boyau', '91220', 'Bretigny sur orge', 'F', 'H', 'toinux@culmouton.com', 'Toinux', '7', 2, '1977-07-27', '', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (41, 'Duroc', 'Nicolas', '78, Avenue de Paris', '92320', 'Chatillon', 'France', 'H', 'jediforce_stg@hotmail.com', 'BaBeuH', '4', 2, '1981-10-28', '0146542566', '0687495097');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (17, 'Verdier', 'Frédéric', '15 Rue Thiers', '26000', 'Valence', 'France', 'H', 'hxh_kass@yahoo.fr', 'Kass', '4', 2, '1982-10-24', '', '0660937347');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (42, 'Metzinger', 'David', '3 chemin des vaugeroux', '95300', 'Pontoise', 'France', 'H', 'frapa95@hotmail.com', 'Frapa', '4', 2, '1980-08-10', '', '0658577827');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (43, 'Stremsdoerfer', 'Jérôme', '107 ter Rue Dalayrac', '94120', 'Fontenay Sous Bois', 'France', '', 'pulverisator@msn.com', 'Pulve', '7', 2, '1976-02-17', '', '0663657666');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (16, 'beziade', 'benoît', '1 rue jean françois lépine', '75018', 'paris', 'fr', 'H', 'winielebarbu@gmail.com', 'bArbu', '3', 2, '1982-10-12', '0140212807', '0664783491');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (8, 'FARINA', 'Franck', '5 rue edouard TIL', '94400', 'Vitry sur seine', 'FRANCE', 'H', 'celos94@yahoo.fr', 'Celos', '3', 1, '1984-07-25', '', '0625691453');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (87, 'LANIECE', 'Denis', '6 place victor jacquemont', '37200', 'Tours', 'france', 'H', 'humu37@wanadoo.fr', 'hUm', '4', 1, '1978-01-17', '', '0684636003');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (38, 'Herreros', 'Jose', '03 rue titon', '75011', 'Paris', 'France', 'H', 'RickBlood@noos.fr', 'Rickii', '7', 1, '1978-08-16', '0143700158', '0622743275');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (86, 'desalmand', 'brice', '7 chemin du clos des sapins', '69260', 'charbonnieres les bains', 'france', 'H', 'calamar124@hotmail.com', 'big-ben-koala', '17', 2, '1979-11-18', '', '0679060279');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (39, 'chayla', 'Jean Marc', '14 rue nationale', '63170', 'Aubière', 'France', 'H', 'killerman63@hotmail.com', 'Latex', '14', 2, '1986-06-30', '', '0682046928');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (53, 'SIERRA', 'David', 'camp d''Hannibal bat g rue du 11 novembre', '07800', 'La Voulte sur Rhône', 'France', 'H', 'onclebensdelt@wanadoo.fr', 'D3lta', '3', 1, '1970-05-10', '0475622185', '0630964807');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (9, 'Sierra', 'Mathieu', '13  castel pavillon', '07800', 'Beauchastel', 'france', 'H', 'Mike_lol@hotmail.com', 'FoNzD', '3', 2, '1985-06-16', '', '0618045023');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (47, 'Herbreteau', 'Romuald', '2 allée René Guy Cadou', '49170', 'La Possonnière', 'France', 'H', 'romuald.herbreteau@wanadoo.fr', 'Flam', '3', 1, '1976-01-28', '', '0662732246');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (40, 'AZNAR', 'Matthieu', '144, rue du Plat d''Etain', '37000', 'Tours (37)', 'France', 'H', 'TiouZi@wanadoo.fr', 'TiouZi', '4', 1, '1978-09-21', '', '0660311995');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (46, 'SZCZEPANSKIKI', 'guillaume', '165 avenue de flandre', '75019', 'Paris', 'France', 'H', 'zhed75@hotmail.com', 'CyRuS', '7', 2, '1983-08-26', '0146078228', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (51, 'Ougab', 'Fathi', '12 rue marx dormoy', '75018', 'Paris', 'France', 'H', 'algrien@hotmail.com', 'alg', '7', 2, '1982-04-16', '0142094103', '0616472754');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (48, 'Arfi', 'Benjamin', '11 rue Suffren', '13120', 'Gardanne', 'France', 'H', 'p4nth3r@wanadoo.fr', 'P4nTh3R', '7', 2, '1981-02-21', '0442517719', '0625421494');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (56, 'redon', 'franck', '53 place des meulieres', '77550', 'moissy cramayel', 'france', 'H', 'ekt.effer@free.fr', 'EffeR', '7', 2, '1966-07-02', '0160600275', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (85, 'Allard', 'Benjamin', '6 place Victor Jacquemont', '37000', 'Tours', 'france', 'H', 'ben187_37@hotmail.com', 'Ben', '4', 1, '1978-08-25', '', '0661903856');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (60, 'Albert', 'Philippe', '11, rue St-Barthélémy', '46000', 'CAHORS', 'France', 'H', 'albphi@hotmail.com', 'AlbPhi', '7', 2, '1982-07-09', '', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (63, 'BERNARD', 'Pascal', '15, rue EdgarDegas', '44570', 'Loire Atlantique', 'France', 'H', 'pascal.bernard62@wanadoo.fr', 'Pibi', '17', 1, '1965-05-07', '0251105688', '0662331794');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (115, 'Negoti', 'stephane', '7 rue de cambrai', '75019', 'paris', 'france', 'H', 'stebo@noos.fr', 'Stebo', '7', 2, '1982-09-12', '0146075885', '0621830288');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (25, 'Lavaux', 'Francois', '15 rue haute du ponceau', '94000', 'Cergy', 'France', 'H', 'kudos_style@hotmail.com', 'Kudos', '3', 1, '1979-10-07', '', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (11, 'LIM', 'Francis', '23 Av Youri Gagarine', '93270', 'Sevran', 'France', 'H', 'cis_cs@yahoo.fr', 'Janus', '7', 2, '1979-02-08', '', '0616177446');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (69, 'ROBIN', 'Thomas', '24 C8 rue Simon Jallade', '69110', 'Sainte Foy Les Lyon', 'France', 'H', 'baxan69@hotmail.com', 'black', '14', 1, '1982-10-22', '', '0661742096');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (70, 'DUMAS', 'Laurent', '18, rue du petit bois', '79000', 'Niort(79)', 'France', 'H', 'lolold@hotmail.com', 'Noir', '14', 1, '1981-11-25', '0549791924', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (98, 'TARDY', 'Lionel', 'Le Perron', '38160', 'Saint Sauveur', 'FRANCE', 'H', 'beelzebud38@hotmail.com', 'beelz', '14', 1, '1984-07-27', '', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (137, 'de DREZIGUE', 'Xavier', '2 rue fernand Pelloutier', '83000', 'TOULON', 'France', 'H', 'xavaude@wanadoo.fr', 'skelet', '14', 1, '1973-03-20', '', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (139, 'LIBERGE', 'Greg', '33 rue des berges', '77700', 'Bailly-Romainvilliers', 'FRANCE', 'H', 'vdzys@hotmail.com', 'CptZeB', '14', 1, '1981-03-26', '', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (124, 'Dumas', 'Aline', '18 rue du petit bois', '79000', 'Niort (79)', 'France', 'F', 'Alinead79@hotmail.com', 'Aline', '14', 2, '1991-01-09', '', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (4, 'lavaux', 'steven', '15 Rue Haute du Ponceau', '95000', 'Cergy', 'France', 'H', 'power_maker@hotmail.com', 'zany', '3', 1, '1986-11-05', '0130732689', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (73, 'Carminati', 'Olivier', '886, rue marc chagall', '77190', 'Dammarie', 'France', 'H', 'ksosclan@free.fr', 'Uboat', '3', 1, '1976-01-19', '', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (151, 'REIGNIER', 'Damien', '3 all Jakes Riou', '29280', 'PLOUZANE', 'FRANCE', 'H', 'tessuo@cegetel.net', 'tetsuo', '14', 2, '1973-04-04', '', '0662551492');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (158, 'MICHELOT', 'STEPHANE', '17 BD DE SUNDERLAND', '44600', 'Loire Atlantique', 'FRANCE', 'H', 'michelotstephane@wanadoo.fr', 'Buteau', '17', 1, '1963-12-03', '0240533794', '0625902996');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (159, 'DOGAN', 'Azim', '18 rue de Bretagne', '25200', 'Grand Charmont', 'France', 'H', 'zim25200@free.fr', 'ZIM', '7', 2, '1978-05-16', '0871055890', '0663722982');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (162, 'Menard', 'Guillaume', '11 avenue Pasteur', '93100', 'Montreuil', 'France', 'H', 'revengersisko93@hotmail.com', 'RevSisko93', '7', 2, '1986-06-03', '0148571781', '0682441516');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (141, 'Lamandé', 'Dorian', 'Ecole Primaire du Château', '77370', 'Nangis', 'France', 'H', 'rhadbouk@yahoo.fr', 'Durex', '7', 1, '1987-05-03', '0164080455', '0688891266');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (169, 'Roelandt', 'Julien.R', 'Rue', '6000', 'Charleroi', 'Belgique', 'H', 'z0rgleet@hotmail.com', 'JayL', '7', 2, '1985-08-12', '/', '0474/367.8');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (28, 'CICEK', 'Yoldas', '43 rue des petites Ecuries', '75010', 'Paris', 'France', 'H', 'ya1hic@free.fr', 'koala', '14', 1, '1979-12-05', '0142466533', '0614858415');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (189, 'Pétré', 'Amaury', '14 rue michel henry', '77440', 'crécy la chapelle', 'france', 'H', 'amaury51@hotmail.com', 'metalmagic', '7', 2, '1982-07-28', '', '0683335338');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (202, 'Alet', 'Fabien', '17 rue Edouard Laferrière', '92190', 'Meudon', 'France', 'H', 'fabienalet@yahoo.fr', 'Shoulders', '7', 2, '1979-08-17', '0146266336', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (201, 'Hierry', 'Kévin', '25, rue du château d''eau', '68740', 'Blodelsheim', 'France', 'H', 'D3pmod@hotmail.fr', 'D3pmod', '7', 2, '1988-10-28', '0389485476', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (207, 'Losenbergh', 'Boris', 'Rue emille vandervelde 113', '7390', 'Quaregnon', 'Belgique', '', 'vicerale217@hotmail.com', 'NarutoKyubi', '7', 2, '1987-12-14', '', '0495.61.59');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (223, 'MENARD', 'Mathieu', '11 avenue pasteur', '93100', 'montreuil sous bois', 'FRANCE', 'H', 'donstar25@hotmail.com', 'DouDou', '17', 1, '1978-09-01', '', '0663061336');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (230, 'guillard', 'christophe', 'chemin de la ville heulin', '44600', 'saint-nazaire', 'france', 'H', 'titiastof@hotmail.fr', 'Ares', '17', 2, '1980-09-08', '', '0677791863');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (71, 'Moussaud', 'Marie-Pierre', '231 avenue Louis ravet bat b', '06700', 'saint laurent du var', 'france', 'F', 'krall@wanadoo.fr', 'KrALL', '3', 1, '1974-03-22', '0492270524', '0661953590');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (32, 'PLUMEJEAU', 'Philippe', '62 Rue Louis Blanc', '37000', 'Tours', 'France', 'H', 'AtomiZer_B52@msn.com', 'AtomiZer', '3', 1, '1969-07-20', '0247055552', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (27, 'Gerland', 'Frederic', '43 allée Camille Claudel', '07500', 'Guilherand-Granges', 'France', 'H', 'cityhunter12002@hotmail.com', 'CitY-HunteR', '16', 2, '1981-04-01', '', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (265, 'gollion', 'amandine', '28 rue guilloux', '69230', 'saint genis laval', 'france', 'F', 'ADN1664@hotmail.com', 'DArk_N', '16', 2, '1983-11-19', '', '0603460816');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (268, 'leggeri', 'antoine', '52 voie de la grange', '95150', 'Taverny', 'france', 'H', 'darkstalkers95@free.fr', 'broly_95', '16', 2, '1980-10-26', '0134180656', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (276, 'martel', 'tiphaine', '15 impass barthere villa 39', '31300', 'toulouse', 'france', 'H', 'marteltiphaine@hotmail.com', 'krg', '16', 2, '1983-11-13', 'aucun', '0616224003');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (269, 'masserot', 'vincent', '1 rue des marsauderies', '44300', 'Nantes', 'france', 'H', 'vince269@caramail.com', 'laspa', '16', 2, '1979-07-31', '', '0663940637');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (275, 'Baradeau', 'François', '19 rue de la Gripière', '78320', 'Levis st Nom', 'France', 'H', 'francinou78@hotmail.com', '0z', '16', 2, '1985-06-10', '0134611284', '0676795592');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (206, 'gagnant', 'mathieu', '16 rue de nexon', '87000', 'Limoges', 'france', 'H', 'math367@hotmail.com', 'TeXaSPoNeY', '16', 2, '1978-06-19', '', '0681479043');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (210, 'ARENE', 'Michael', 'Le 4L1  357 rue Marc et Yvonne Baron', '83000', 'Toulon', 'France', 'H', 'drag0n_n0ir@hotmail.com', 'Dragon', '14', 1, '1984-07-06', '0872231602', '0625111330');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (213, 'Espagnol', 'Gregory', '105 rue du sabot', '38660', 'La terrasse', 'France', 'H', 'greg38@lavache.com', 'Leerd', '15', 2, '1977-06-18', '', '0631151755');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (282, 'GRAIN', 'boris', 'Hameau de bellegarde', '76190', 'Rouen', 'France', 'H', 'bobogo_76@hotmail.com', 'bobog', '15', 1, '1980-01-26', '', '0616547452');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (281, 'Lopez', 'Romain', '51 C rue du coq saint marceau', '45100', 'Orléans', 'France', 'H', 'rom145@hotmail.com', 'CaPrice', '15', 2, '1988-04-07', '0238560964', '0603297481');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (286, 'Trabut', ' romain', '7 rue henri moissan', '38000', 'isere', 'france', 'H', 'crevette38@lavache.com', 'Gouda', '15', 1, '1979-09-21', '', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (288, 'Mathieu', 'Jerome', '31 rue d''arsonval', '69800', 'Saint Priest', 'France', 'H', 'emoman@free.fr', 'Parmesan', '15', 2, '1986-01-20', '', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (277, 'Gendre', 'Julien', '150 bd Voltaire', '92600', 'Asnières sur Seine', 'France', 'H', 'julliien@hotmail.com', 'Chavroux', '15', 1, '1982-08-02', '', '0668970620');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (204, 'MESSINA', 'Gabriel-Emmanuel', '5, chemin de l''église', '38000', 'Grenoble', 'France', 'H', 'gabs119@hotmail.com', 'St-MarS', '15', 1, '1977-05-28', '', '0607901395');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (291, 'bats', 'sebastien', '86 citée montadour', '40500', 'st-sever', 'france', 'H', 'sbatsou@hotmail.com', 'Cabecou', '15', 2, '1976-10-05', '', '0624127077');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (294, 'stagne', 'cyril', 'les ardrets', '91220', 'bretigny', 'france', 'H', 'cyrnad2@free.fr', 'cyrnad', '7', 2, '1977-03-06', '0000000000', '0000000000');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (290, 'sanchez', 'pablo', '1, rue choderlos de laclos appt 334', '75013', 'paris', 'france', 'H', 'zildjian-@hotmail.fr', 'zildjian-', '7', 2, '1974-07-23', '0153619893', '0612964472');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (297, 'CAO VAN', 'Christian', 'rue du fossé st Denis', '84400', 'GARGAS', 'FRANCE', 'H', 'chriselix@hotmail.com', 'Tx', '14', 1, '1983-11-29', '', '0677751538');
