-- phpMyAdmin SQL Dump
-- version 2.6.4-pl4-Debian-2
-- http://www.phpmyadmin.net
-- 
-- Serveur: sql-1.verygames.net
-- Généré le : Lundi 28 Novembre 2005 à 00:01
-- Version du serveur: 4.1.14
-- Version de PHP: 4.4.0-4
-- 
-- Base de données: `server60`
-- 

-- --------------------------------------------------------

-- 
-- Structure de la table `adhesion_adherents`
-- 

CREATE TABLE "adhesion_adherents" (
  "adh_id" int(11) NOT NULL default '0',
  "adh_nom" varchar(40) NOT NULL default '',
  "adh_prenom" varchar(30) NOT NULL default '',
  "adh_adresse" varchar(100) NOT NULL default '',
  "adh_code_postal" varchar(10) NOT NULL default '',
  "adh_ville" varchar(30) NOT NULL default '',
  "adh_pays" varchar(20) NOT NULL default '',
  "adh_sexe" char(1) NOT NULL default '',
  "adh_email" varchar(100) NOT NULL default '',
  "adh_pseudo" varchar(30) NOT NULL default '',
  "adh_equipe" varchar(30) NOT NULL default '',
  "adh_statut" int(11) NOT NULL default '2',
  "adh_date_naissance" date NOT NULL default '0000-00-00',
  "adh_telephone_fixe" varchar(14) NOT NULL default '',
  "adh_telephone_portable" varchar(14) NOT NULL default '',
  PRIMARY KEY  ("adh_id"),
  KEY "pseudo" ("adh_pseudo")
);

-- 
-- Contenu de la table `adhesion_adherents`
-- 

INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (2, 'Dorso', 'Erwan', '46 bis rue Jacques Provost', '31200', 'toulouse', 'france', 'H', 'heroined@mageos.com', 'karamazov', '3', 1, '1975-10-26', '0534309159', '0663875230');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (65, 'Spengler', 'Fabien', '53 rue planchat', '75020', 'Paris', 'France', 'H', 'fab.mail@laposte.fr', 'KlocheTTe', '3', 1, '1975-03-13', '0870370535', '0622230535');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (3, 'Montadre', 'Sébastien', '43 rue Ernest Renan', '92190', 'Meudon', 'France', 'H', 'slapinou@gmail.com', 'Slapinou', '3', 1, '1979-10-03', '0145078609', '0684476845');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (59, 'Carry', 'Lionel', '6 bis rue Robert Julien', '92190', 'Meudon', 'France', 'H', 'coeurdelio@hotmail.com', 'Lilo', '3', 1, '1980-05-09', '0145346087', '0660233488');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (7, 'LEAUTE', 'Sébastien', '202 rue Hector Berlioz', '41100', 'Vendome', 'France', 'H', 'macleote@msn.com', 'GPX', '3', 1, '1976-11-21', '0254731326', '0611178984');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (45, 'DEBOVE', 'Florent', '10 rue Mulet', '38460', 'CREMIEU', 'FRANCE', 'H', 'korozif@ekt.fr.st', 'KoRoZiF', '11', 1, '1969-09-21', '0437061162', '0665005120');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (13, 'GRIFFOULIERE', 'Guillaume', '20 rue du Saget', '74100', 'Annemasse', 'France', 'H', 'coredumped@culmouton.com', 'Core Dumped', '5', 1, '1979-03-02', '0450375293', '0612337039');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (14, 'Desneux', 'Nicolas', 'Indianapolis', 'c''est usa.', 'Indianapolis/Tours', 'USA', 'H', 'nicux@msn.com', 'Nicux', '5', 1, '1975-01-19', 'nothing', 'nothing');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (44, 'Moerman', 'Alain', '45 rue neuve', '44320', 'st pere en retz', 'France', 'F', 'inscription.lettre@wanadoo.fr', 'ZuuR', '11', 1, '1971-02-25', '', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (12, 'Lenoir', 'Jean-Christophe', '125, rue Goerge Sand', '37000', 'Tours', 'France', 'H', 'jcex@culmouton.com', 'JCex', '5', 1, '1978-05-03', '0234381121', '0664320503');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (21, 'Dumont', 'Philippe', '8, rue de la Paix', '63910', 'Vertaizon', 'France', 'H', 'campbell@culmouton.com', 'Campbell', '5', 1, '1981-05-12', '', '0662520439');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (19, 'LETOURNEL', 'Julien', '2 bd Jean Bouin', '77370', 'NANGIS', 'France', 'H', 'makaveli@24kra.net', 'makaveLi', '4', 1, '1985-02-17', '0164081220', '0683203519');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (30, 'Morel', 'Aurélien', 'Rue du Midi 17b', '1400', 'Yverdon', 'Suisse', '', 'aurelien.morel@freesurf.ch', 'Olmolism', '7', 1, '1980-09-15', '', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (31, 'Cabrelli', 'Clément', '82 rue des roissys', '92320', 'chatillon', 'france', 'H', 'skax@brutalrush.com', 'SkaX', '4', 1, '1981-03-07', '0158882899', '0622088871');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (18, 'Taleb', 'Kamel', '3 allée du languedoc', '95310', 'Saint ouen l''aumône', 'France', 'H', 'tounsi007@msn.com', 'Onkyo', '4', 1, '1978-09-16', '0134300653', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (37, 'Louison-François', 'Mickaël', '72 rue Bernard Palissy', '37000', 'TOURS', 'France', 'H', 'its.m@wanadoo.fr', 'ITS', '4', 1, '1973-09-02', '', '0661717630');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (81, 'Chaffiol', 'Antoine', '6 rue maurice boyau', '91220', 'Bretigny sur orge', 'F', 'H', 'toinux@culmouton.com', 'Toinux', '5', 1, '1977-07-27', '', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (41, 'Duroc', 'Nicolas', '78, Avenue de Paris', '92320', 'Chatillon', 'France', 'H', 'jediforce_stg@hotmail.com', 'BaBeuH', '4', 1, '1981-10-28', '0146542566', '0687495097');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (17, 'Verdier', 'Frédéric', '15 Rue Thiers', '26000', 'Valence', 'France', 'H', 'hxh_kass@yahoo.fr', 'Kass', '4', 1, '1982-10-24', '', '0660937347');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (42, 'Metzinger', 'David', '3 chemin des vaugeroux', '95300', 'Pontoise', 'France', 'H', 'frapa95@hotmail.com', 'Frapa', '4', 1, '1980-08-10', '', '0658577827');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (43, 'Stremsdoerfer', 'Jérôme', '107 ter Rue Dalayrac', '94120', 'Fontenay Sous Bois', 'France', '', 'pulverisator@msn.com', 'Pulve', '11', 1, '1976-02-17', '', '0663657666');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (16, 'beziade', 'benoît', '126 avenue de saxe', '69003', 'lyon', 'fr', 'H', 'winielebarbu@hotmail.com', 'bArbu', '3', 1, '1982-10-12', '0478602845', '0664783491');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (8, 'FARINA', 'Franck', '5 rue edouard TIL', '94400', 'Vitry sur seine', 'FRANCE', 'H', 'celos94@yahoo.fr', 'Celos', '3', 1, '1984-07-25', '', '0625691453');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (87, 'LANIECE', 'Denis', '6 place victor jacquemont', '37200', 'Tours', 'france', 'H', 'humu37@wanadoo.fr', 'hUm', '4', 1, '1978-01-17', '', '0684636003');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (38, 'Herreros', 'Jose', '03 rue titon', '75011', 'Paris', 'France', 'H', 'RickBlood@noos.fr', 'Rickii', '4', 1, '1978-08-16', '0143700158', '0622743275');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (86, 'desalmand', 'brice', '7 chemin du clos des sapins', '69260', 'charbonnieres les bains', 'france', 'H', 'calamar124@hotmail.com', 'big-ben-koala', '11', 1, '1979-11-18', '', '0679060279');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (39, 'chayla', 'Jean Marc', '14 rue nationale', '63170', 'Aubière', 'France', 'H', 'killerman63@hotmail.com', 'Latex', '5', 1, '1986-06-30', '', '0682046928');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (53, 'SIERRA', 'David', 'camp d''Hannibal bat g rue du 11 novembre', '07800', 'La Voulte sur Rhône', 'France', 'H', 'onclebensdelt@wanadoo.fr', 'D3lta', '3', 1, '1970-05-10', '0475622185', '0630964807');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (9, 'Sierra', 'Mathieu', '13  castel pavillon', '07800', 'Beauchastel', 'france', 'H', 'Mike_lol@hotmail.com', 'FoNzD', '3', 1, '1985-06-16', '', '0618045023');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (47, 'Herbreteau', 'Romuald', '2 allée René Guy Cadou', '49170', 'La Possonnière', 'France', 'H', 'romuald.herbreteau@wanadoo.fr', 'Flam', '3', 1, '1976-01-28', '', '0662732246');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (40, 'AZNAR', 'Matthieu', '144, rue du Plat d''Etain', '37000', 'Tours (37)', 'France', 'H', 'TiouZi@wanadoo.fr', 'TiouZi', '4', 1, '1978-09-21', '', '0660311995');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (46, 'SZCZEPANSKIKI', 'guillaume', '165 avenue de flandre', '75019', 'Paris', 'France', 'H', 'zhed75@hotmail.com', 'CyRuS', '11', 1, '1983-08-26', '0146078228', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (51, 'Ougab', 'Fathi', '12 rue marx dormoy', '75018', 'Paris', 'France', 'H', 'algrien@hotmail.com', 'alg', '11', 1, '1982-04-16', '0142094103', '0616472754');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (48, 'Arfi', 'Benjamin', '11 rue Suffren', '13120', 'Gardanne', 'France', 'H', 'p4nth3r@wanadoo.fr', 'P4nTh3R', '7', 1, '1981-02-21', '0442517719', '0625421494');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (56, 'redon', 'franck', '53 place des meulieres', '77550', 'moissy cramayel', 'france', 'H', 'ekt.effer@free.fr', 'EffeR', '11', 1, '1966-07-02', '0160600275', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (85, 'Allard', 'Benjamin', '6 place Victor Jacquemont', '37000', 'Tours', 'france', 'H', 'ben187_37@hotmail.com', 'Ben', '4', 1, '1978-08-25', '', '0661903856');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (60, 'Albert', 'Philippe', '11, rue St-Barthélémy', '46000', 'CAHORS', 'France', 'H', 'albphi@hotmail.com', 'AlbPhi', '7', 1, '1982-07-09', '', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (63, 'BERNARD', 'Pascal', '15, rue EdgarDegas', '44570', 'Loire Atlantique', 'France', 'H', 'pascal.bernard62@wanadoo.fr', 'Pibi', '7', 1, '1965-05-07', '0251105688', '0662331794');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (115, 'Negoti', 'stephane', '7 rue de cambrai', '75019', 'paris', 'france', 'H', 'stebo@noos.fr', 'Stebo', '11', 1, '1982-09-12', '0146075885', '0621830288');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (25, 'Lavaux', 'Francois', '15 rue haute du ponceau', '94000', 'Cergy', 'France', 'H', 'kudos_style@hotmail.com', 'Kudos', '7', 1, '1979-10-07', '', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (11, 'LIM', 'Francis', '23 Av Youri Gagarine', '93270', 'Sevran', 'France', 'H', 'cis_cs@yahoo.fr', 'Janus', '7', 1, '1979-02-08', '', '0616177446');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (69, 'ROBIN', 'Thomas', '24 C8 rue Simon Jallade', '69110', 'Sainte Foy Les Lyon', 'France', 'H', 'baxan69@hotmail.com', 'black', '14', 1, '1982-10-22', '', '0661742096');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (70, 'DUMAS', 'Laurent', '18, rue du petit bois', '79000', 'Niort(79)', 'France', 'H', 'lolold@hotmail.com', 'Noir', '14', 1, '1981-11-25', '0549791924', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (98, 'TARDY', 'Lionel', 'Le Perron', '38160', 'Saint Sauveur', 'FRANCE', 'H', 'beelzebud38@hotmail.com', 'beelz', '14', 1, '1984-07-27', '', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (137, 'de DREZIGUE', 'Xavier', '2 rue fernand Pelloutier', '83000', 'TOULON', 'France', 'H', 'xavaude@wanadoo.fr', 'skelet', '14', 1, '1973-03-20', '', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (139, 'LIBERGE', 'Greg', '33 rue des berges', '77700', 'Bailly-Romainvilliers', 'FRANCE', 'H', 'vdzys@hotmail.com', 'CptZeB', '14', 1, '1981-03-26', '', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (124, 'Dumas', 'Aline', '18 rue du petit bois', '79000', 'Niort (79)', 'France', 'F', 'Alinead79@hotmail.com', 'Aline', '14', 1, '1991-01-09', '', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (4, 'lavaux', 'steven', '15 Rue Haute du Ponceau', '95000', 'Cergy', 'France', 'H', 'power_maker@hotmail.com', 'zany', '7', 1, '1986-11-05', '0130732689', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (73, 'Carminati', 'Olivier', '886, rue marc chagall', '77190', 'Dammarie', 'France', 'H', 'ksosclan@free.fr', 'Uboat', '3', 1, '1976-01-19', '', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (151, 'REIGNIER', 'Damien', '3 all Jakes Riou', '29280', 'PLOUZANE', 'FRANCE', 'H', 'tessuo@cegetel.net', 'tetsuo', '14', 1, '1973-04-04', '', '0662551492');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (158, 'MICHELOT', 'STEPHANE', '17 BD DE SUNDERLAND', '44600', 'Loire Atlantique', 'FRANCE', 'H', 'michelotstephane@wanadoo.fr', 'Buteau', '7', 1, '1963-12-03', '0240533794', '0625902996');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (159, 'DOGAN', 'Azim', '18 rue de Bretagne', '25200', 'Grand Charmont', 'France', 'H', 'zim25200@free.fr', 'ZIM', '5', 1, '1978-05-16', '0871055890', '0663722982');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (162, 'Menard', 'Guillaume', '11 avenue Pasteur', '93100', 'Montreuil', 'France', 'H', 'revengersisko93@hotmail.com', 'RevSisko93', '7', 1, '1986-06-03', '0148571781', '0682441516');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (141, 'Lamandé', 'Dorian', 'Ecole Primaire du Château', '77370', 'Nangis', 'France', 'H', 'rhadbouk@yahoo.fr', 'Durex', '5', 1, '1987-05-03', '0164080455', '0688891266');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (169, 'Roelandt', 'Julien.R', 'Rue', '6000', 'Charleroi', 'Belgique', 'H', 'z0rgleet@hotmail.com', 'JayL', '7', 1, '1985-08-12', '/', '0474/367.8');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (28, 'CICEK', 'Yoldas', '43 rue des petites Ecuries', '75010', 'Paris', 'France', 'H', 'ya1hic@free.fr', 'koala', '14', 1, '1979-12-05', '0142466533', '0614858415');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (189, 'Pétré', 'Amaury', '14 rue michel henry', '77440', 'crécy la chapelle', 'france', 'H', 'amaury51@hotmail.com', 'metalmagic', '7', 1, '1982-07-28', '', '0683335338');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (202, 'Alet', 'Fabien', '17 rue Edouard Laferrière', '92190', 'Meudon', 'France', 'H', 'fabienalet@yahoo.fr', 'Shoulders', '7', 1, '1979-08-17', '0146266336', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (201, 'Hierry', 'Kévin', '25, rue du château d''eau', '68740', 'Blodelsheim', 'France', 'H', 'D3pmod@hotmail.fr', 'D3pmod', '7', 2, '1988-10-28', '0389485476', '');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (207, 'Losenbergh', 'Boris', 'Rue emille vandervelde 113', '7390', 'Quaregnon', 'Belgique', '', 'vicerale217@hotmail.com', 'NarutoKyubi', '7', 2, '1987-12-14', '', '0495.61.59');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (223, 'MENARD', 'Mathieu', '11 avenue pasteur', '93100', 'montreuil sous bois', 'FRANCE', 'H', 'donstar25@hotmail.com', 'DouDou', '7', 1, '1978-09-01', '', '0663061336');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (230, 'guillard', 'christophe', 'chemin de la ville heulin', '44600', 'saint-nazaire', 'france', 'H', 'titiastof@hotmail.fr', 'Ares', '7', 1, '1980-09-08', '', '0677791863');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (71, 'moussaud', 'Marie-Pierre', '231 avenue Louis ravet bat b', '06700', 'saint laurent du var', 'france', 'F', 'krall@wanadoo.fr', 'KrALL', '3', 2, '1974-03-22', '0492270524', '0661953590');
INSERT INTO `adhesion_adherents` (`adh_id`, `adh_nom`, `adh_prenom`, `adh_adresse`, `adh_code_postal`, `adh_ville`, `adh_pays`, `adh_sexe`, `adh_email`, `adh_pseudo`, `adh_equipe`, `adh_statut`, `adh_date_naissance`, `adh_telephone_fixe`, `adh_telephone_portable`) VALUES (32, 'PLUMEJEAU', 'Philippe', '62 Rue Louis Blanc', '37000', 'Tours', 'France', 'H', 'AtomiZer_B52@msn.com', 'AtomiZer', '3', 2, '1969-07-20', '0247055552', '');

-- --------------------------------------------------------

-- 
-- Structure de la table `adhesion_config`
-- 

CREATE TABLE "adhesion_config" (
  "cfg_groupes" varchar(20) NOT NULL default '',
  "cfg_textaccueil" text NOT NULL,
  "cfg_periode" int(11) NOT NULL default '0'
);

-- 
-- Contenu de la table `adhesion_config`
-- 

INSERT INTO `adhesion_config` (`cfg_groupes`, `cfg_textaccueil`, `cfg_periode`) VALUES ('', '<span class="HEADER">Condition d’inscription</span>\r\n<p>\r\nL’adhésion à la Cassosiation est soumise à certaines conditions:\r\n</p>\r\n<ol>\r\n<li>Etre majeur</li>\r\n<li>Avoir lu et approuvé la charte de l’adhérent disponible <a href="/npds/sections.php?op=viewarticle&artid=5" target=_blank>ICI</a></li>\r\n<li>Remplir le formulaire ci-dessous en fournissant les coordonnées nécessaires</li>\r\n</ol>\r\n<p>\r\nUne fois le formulaire rempli, <b>votre adhésion soumise à l’approbation du Conseil d’Administration de l’association et sera validée à la réception de votre cotisation</b>.\r\n</p>\r\n<p>\r\nLes coordonnées pour envoyer votre paiement sont disponibles <a href="/npds/modules.php?ModPath=phpBB2&ModStart=viewtopic&p=1217#1217" target=_blank>ICI</a>\r\n</p>\r\n<br><br>\r\n<font size=-2><i>Les informations recueillies sont nécessaires\r\npour votre adhésion. Elles font l’objet d’un traitement informatique et\r\nsont destinées au secrétariat de l’association. En application de\r\nl’article 34 de la loi du 6 janvier 1978, vous bénéficiez d’un droit\r\nd’accès et de rectification aux informations qui vous concernent. Si\r\nvous souhaitez exercer ce droit veuillez utiliser l’accès par le module adhésion\r\nmis à votre disposition en première page. Pour toute autre demande ou requête,\r\nveuillez vous adresser au président de l’association (coordonnées disponible sur le site)\r\n</i>\r\n</font>', 0);

-- --------------------------------------------------------

-- 
-- Structure de la table `adhesion_config_tab`
-- 

CREATE TABLE "adhesion_config_tab" (
  "id" int(11) NOT NULL,
  "parametre" varchar(20) NOT NULL default '',
  "valeur" text NOT NULL,
  PRIMARY KEY  ("id")
) AUTO_INCREMENT=134 ;

-- 
-- Contenu de la table `adhesion_config_tab`
-- 

INSERT INTO `adhesion_config_tab` (`id`, `parametre`, `valeur`) VALUES (1, 'cfg_txt_accueil', '<span class="HEADER">Conditions d’inscription</span>\r\n<p>\r\nL’adhésion à la Cassosiation est soumise à certaines conditions:\r\n</p>\r\n<ol>\r\n<li>Etre majeur</li>\r\n<li>Avoir lu et approuvé la charte de l’adhérent disponible <a href="/npds/sections.php?op=viewarticle&artid=5" target=_blank>ICI</a></li>\r\n<li>Remplir le formulaire ci-dessous en fournissant toutes les coordonnées demandées</li>\r\n</ol>\r\n<p>\r\nUne fois ce formulaire rempli, <b>votre adhésion sera soumise à l’approbation du Conseil d’Administration de l’association et sera validée à la réception de votre cotisation</b>.\r\n</p><br>\r\n<p>Pour  votre paiement :<br>\r\n<ul>\r\n<li>si c’est un chèque vous trouverez les coordonnées pour l’envoi et l’ordre <a href="/npds/sections.php?op=viewarticle&artid=18" target=_blank>ICI</a></li>\r\n<li>si c’est un virement vous trouverez le RIB de l’association <a href="/npds/sections.php?op=viewarticle&artid=13" target=_blank>ICI</a></li>\r\n</ul>\r\n</p>\r\n<br>\r\n<font size=-2><i>Les informations recueillies sont nécessaires\r\npour votre adhésion. Elles font l’objet d’un traitement informatique et\r\nsont destinées au secrétariat de l’association. En application de\r\nl’article 34 de la loi du 6 janvier 1978, vous bénéficiez d’un droit\r\nd’accès et de rectification aux informations qui vous concernent. Si\r\nvous souhaitez exercer ce droit veuillez utiliser l’accès par le module adhésion\r\nmis à votre disposition en première page. Pour toute autre demande ou requête,\r\nveuillez vous adresser au président de l’association (coordonnées disponible sur le site)\r\n</i>\r\n</font>');
INSERT INTO `adhesion_config_tab` (`id`, `parametre`, `valeur`) VALUES (2, 'cfg_date_start', '2004-12-26');
INSERT INTO `adhesion_config_tab` (`id`, `parametre`, `valeur`) VALUES (133, 'cfg_groupe5', '16');
INSERT INTO `adhesion_config_tab` (`id`, `parametre`, `valeur`) VALUES (132, 'cfg_groupe4', '15');
INSERT INTO `adhesion_config_tab` (`id`, `parametre`, `valeur`) VALUES (7, 'cfg_bloc_contenu', '<li><a href="modules.php?ModPath=adhesions&amp;ModStart=adhesion_formulaire"><b>Adhésion</b></a></li>\r\n<hr class="SEPAR"><li><a href="sections.php?op=viewarticle&amp;artid=1">Présentation</a></li>\r\n<li><a href="sections.php?op=viewarticle&amp;artid=6">Conseil Administration</a></li>\r\n<li><a href="links.php?op=viewslink&amp;sid=9">Membres</a></li>\r\n<li><a href="loi1901.pdf" target="_blank">Loi 1901</a></li>\r\n<hr class="SEPAR"><li><a href="sections.php?op=viewarticle&amp;artid=5">Charte adhérent</a></li>\r\n<li><a href="sections.php?op=viewarticle&amp;artid=4">Chartes Serveurs</a>');
INSERT INTO `adhesion_config_tab` (`id`, `parametre`, `valeur`) VALUES (8, 'cfg_bloc_titre', 'cassosiation');
INSERT INTO `adhesion_config_tab` (`id`, `parametre`, `valeur`) VALUES (131, 'cfg_groupe3', '14');
INSERT INTO `adhesion_config_tab` (`id`, `parametre`, `valeur`) VALUES (130, 'cfg_groupe2', '7');
INSERT INTO `adhesion_config_tab` (`id`, `parametre`, `valeur`) VALUES (80, 'cfg_nb_sessions', '3');
INSERT INTO `adhesion_config_tab` (`id`, `parametre`, `valeur`) VALUES (129, 'cfg_groupe1', '4');
INSERT INTO `adhesion_config_tab` (`id`, `parametre`, `valeur`) VALUES (128, 'cfg_groupe0', '3');

-- --------------------------------------------------------

-- 
-- Structure de la table `adhesion_cotisations`
-- 

CREATE TABLE "adhesion_cotisations" (
  "cot_id" int(11) unsigned NOT NULL,
  "cot_adh_id" int(30) NOT NULL default '0',
  "cot_montant" float default NULL,
  "cot_date" date default NULL,
  "cot_session" int(11) unsigned default NULL,
  "cot_type" int(10) unsigned default NULL,
  "cot_comments" varchar(100) default NULL,
  "cot_reference" varchar(20) default NULL,
  PRIMARY KEY  ("cot_id")
) AUTO_INCREMENT=92 ;

-- 
-- Contenu de la table `adhesion_cotisations`
-- 

INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (6, 30, 50, '2004-12-10', 1, 1, 'Mandat international à Fabien Spengler --> Dépot espèce', '04 3072089 G');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (7, 43, 80, '2004-10-29', 1, 1, '', '3813176');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (8, 45, 80, '2004-10-17', 1, 1, '', '6204741');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (13, 44, 45, '2004-12-02', 1, 1, 'Chèque1 : 04 4652016 F\r\n\r\n', '04 4652016 F');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (35, 44, 45, '2004-12-02', 1, 1, 'Chèque2 : 04 4652017 F', '04 4652017 F');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (10, 13, 65, '2004-11-08', 1, 1, '', '0000281');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (21, 7, 55, '2004-11-19', 1, 1, '', '9594656');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (14, 12, 75, '2004-10-11', 1, 1, '', '6573158');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (15, 18, 54.2, '2004-12-06', 1, 1, '', '6573158');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (16, 31, 54.2, '2004-12-07', 1, 1, '', '7463992');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (17, 37, 54.2, '2004-12-06', 1, 1, '', '04 4429020 B');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (18, 40, 54.2, '2004-12-15', 1, 1, '', '2409516');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (19, 87, 54.2, '2004-12-15', 1, 1, '', '2409516');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (20, 2, 100, '2004-11-26', 1, 1, '', '04 4633004 F');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (22, 53, 55, '2004-11-07', 1, 1, 'Chèque de 110€ - Bénéficiaires : D3lta et FonzD', '0188782');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (23, 9, 55, '2004-11-07', 1, 1, 'Chèque de 110€ - Bénéficiaires : D3lta et FonzD', '0188782');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (24, 3, 60, '2004-11-07', 1, 3, 'Versés à Klochette', '');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (25, 8, 25, '2004-12-12', 1, 1, '', '02 2677011 B');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (26, 41, 54.2, '2004-12-07', 1, 1, '', '7463992');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (27, 38, 54.2, '2004-12-22', 1, 2, 'Herrero pour Cassosiation', '');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (28, 48, 50, '2005-01-03', 1, 2, 'Nancy Daumas - Cotisation P4nther', '');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (31, 42, 54.2, '2004-12-14', 1, 1, '', '0000067');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (32, 81, 65, '2004-12-08', 1, 1, '', '0198364');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (33, 19, 30, '2004-12-30', 1, 1, '', '2361831');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (34, 47, 35, '2004-12-30', 1, 1, '', '0000031');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (53, 60, 50, '2005-01-31', 1, 1, 'FreePlayer', '0000001');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (54, 63, 50, '2005-02-16', 1, 2, 'BERNARD  COTISATION', '');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (39, 85, 54.2, '2004-12-15', 1, 1, '', '2409516');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (40, 56, 80, '2005-01-02', 1, 1, '', '2127485');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (41, 46, 80, '2004-12-21', 1, 1, '', '1022763');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (44, 16, 25, '2005-01-11', 1, 3, '', '');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (45, 21, 65, '2004-01-17', 1, 1, 'Chèque de 130€ - Bénéficiaires : Campbell et Latex', '8993891');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (46, 39, 65, '2005-01-17', 1, 1, 'Chèque de 130€ - Bénéficiaires : Campbell et Latex', '8993891');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (47, 12, 30, '2005-01-25', 1, 2, 'Virement de 165€ au total - Bénéficiaire : Nicux 65€ - Luther 40€ - ZIM 30€ - Durex 30€', '');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (48, 51, 80, '2005-01-25', 1, 2, 'MR OUGAB FATHI COTISATION ALG', 'Cotisation Alg');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (49, 14, 65, '2005-01-25', 1, 2, 'Virement de 165€ au total - Bénéficiaire : Nicux 65€ - Luther 40€ - ZIM 30€ - Durex 30€', '');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (50, 59, 25, '2005-01-28', 1, 1, 'Chèque de 80€ de Mr Carry - Bénéficiaire :  Lilo (15€) ---> Attend complément de 10€ par Slapinou', '');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (51, 65, 65, '2005-01-28', 1, 1, 'Chèque de 80€ de Mr Carry - Bénéficiaire : KlocheTTe (65 €)', '0109869');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (52, 17, 65.7, '2005-02-08', 1, 1, '3 chèques précédents non-signés, non-encaissés, détruits (0000087, 0000088, 0000089)', '0470005');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (55, 70, 70, '2005-02-14', 1, 1, 'Chèque commun avec Aline', '5546713');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (56, 98, 55, '2005-02-19', 1, 1, '', '5446557');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (57, 69, 45, '2005-02-26', 1, 2, 'ROBIN THOMAS COTISE ELI BLACK', '');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (58, 3, 30, '2005-02-26', 1, 2, 'Cotis. compl. slap', '');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (59, 124, 70, '2005-02-27', 1, 1, 'Chèque commun avec Noir', '5546713');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (60, 11, 50, '2005-03-03', 1, 2, 'VIREMENT LIM FRA', '');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (61, 25, 150, '2005-03-03', 1, 2, 'DON POUR CASSOSIATION BY KUDOS - 300€ en tout', '');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (62, 4, 150, '2005-03-03', 1, 2, 'DON POUR CASSOSIATION BY KUDOS - 300€ en tout', '');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (64, 86, 80, '2005-03-04', 1, 1, 'date = date de dépôt', '8173306');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (65, 115, 80, '2005-03-04', 1, 1, 'date = date de dépôt\r\n', '04 4632013 B');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (66, 139, 55, '2005-03-04', 1, 1, 'date = date de dépôt du chèque', '4741007');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (67, 137, 65, '2005-03-04', 1, 1, 'date = date de dépôt du chèque', '0000227');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (68, 73, 40, '2005-01-04', 1, 1, '', '02 2596014 B');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (69, 7, 30, '2005-04-08', 1, 2, 'Compl. Cotis. Gpx', '');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (70, 16, 20, '2005-04-09', 1, 2, 'Compl. Cotis. Barbu', '');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (71, 65, 30, '2005-04-13', 1, 3, ' Compl. Cotis.KlocheTTe', '');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (72, 151, 70, '2005-03-16', 1, 1, '', '04 4631015 E');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (73, 69, 25, '2005-03-12', 1, 2, 'Compl. Cot. Black', '');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (74, 159, 40, '2005-05-02', 1, 2, 'Virement de 165€ au total - Bénéficiaire : Nicux 65€ - Luther 40€ - ZIM 30€ - Durex 30€', '');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (75, 53, 50, '2005-04-29', 1, 2, 'Compl. Cotis. D3lt@', '');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (76, 162, 25, '2005-05-18', 1, 1, '', '');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (77, 141, 30, '2005-01-25', 1, 2, 'Virement de 165€ au total - Bénéficiaire : Nicux 65€ - Luther 40€ - ZIM 30€ - Durex 30€', '');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (78, 169, 25, '2005-06-06', 1, 1, '<br>Il faut rentrer le n° de chèque</b>', '');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (79, 158, 25, '2005-06-02', 1, 1, '', '8072484');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (80, 28, 54, '2005-06-09', 1, 2, 'YOLDAS CICEK - COTISATION ELI KOALA', '');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (81, 202, 25, '2005-08-01', 1, 2, 'Virement de 50€ de sébastien Montadre - Bénéficiaires : Doggpound + Shoulders', '');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (82, 189, 25, '2005-09-29', 1, 2, 'M. PETRE AMAURY<br>\r\nCOTISATION FUNXP METALMAGIC', '');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (83, 223, 25, '2005-10-01', 1, 1, 'METTRE LE N° DE CHEQUE', '');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (84, 230, 25, '2005-10-11', 1, 2, 'M CHRISTOPHE GUILLARD', '');
INSERT INTO `adhesion_cotisations` (`cot_id`, `cot_adh_id`, `cot_montant`, `cot_date`, `cot_session`, `cot_type`, `cot_comments`, `cot_reference`) VALUES (91, 69, 40, '2005-11-25', 1, 2, 'ROBIN THOMAS\r\nCOTISATION ELI BLACK', '');
